workflows:
  ios:
    name: iOS Build
    max_build_duration: 60
    environment:
      vars:
        FLUTTER_VERSION: "stable"
    triggers:
      on:
        push:
          branches:
            only:
              - main
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
