name: pkm_gastreit
description: "A new Flutter project."
publish_to: 'none'
version: 1.3.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  provider: ^6.1.2
  flutter_launcher_icons: ^0.13.1
  firebase_auth: ^4.16.0
  image_picker: ^1.1.2
  avatars: ^3.0.2
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  cached_network_image: ^3.3.1
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  image_path: "images/logo.png" 

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    - images/landing_1.png
    - images/landing_2.png
    - images/landing_3.png
    - images/logo_google.png
    - images/Icon-InputCitra.png
    - images/Icon-HasilCitra.png
    - images/informasimenarik1.png
    - images/informasimenarik2.png
    - images/informasimenarik3.png
    - images/informasimenarik4.png
    - images/informasimenarik5.png
    - images/home_black.png
    - images/input_light.png
    - images/hasil_light.png
    - images/hasil_black.png
    - images/home_light.png
    - images/input_black.png
    - images/chat_light.png
    - images/chat_black.png
    - images/avatar1.png
    - images/avatar2.png

