name: pkm_gastreit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # fonts:
    # - family: Ubuntu
    #   fonts:
    #     - asset: fonts/Ubuntu/Ubuntu-Regular.ttf
    #     - asset: fonts/Ubuntu/Ubuntu-Bold.ttf
    #     - asset: fonts/Ubuntu/Ubuntu-Italic.ttf
    #     - asset: fonts/Ubuntu/Ubuntu-BoldItalic.ttf
    #     - asset: fonts/Ubuntu/Ubuntu-Light.ttf
    #     - asset: fonts/Ubuntu/Ubuntu-LightItalic.ttf
    #     - asset: fonts/Ubuntu/Ubuntu-Medium.ttf
    #     - asset: fonts/Ubuntu/Ubuntu-MediumItalic.ttf
    # - family: Murecho
    #   fonts:
    #     - asset: fonts/Murecho/static/Murecho-Bold.ttf
    #     - asset: fonts/Murecho/static/Murecho-ExtraBold.ttf
    #     - asset: fonts/Murecho/static/Murecho-ExtraLight.ttf
    #     - asset: fonts/Murecho/static/Murecho-Light.ttf
    #     - asset: fonts/Murecho/static/Murecho-Medium.ttf
    #     - asset: fonts/Murecho/static/Murecho-Regular.ttf
    #     - asset: fonts/Murecho/static/Murecho-SemiBold.ttf
    #     - asset: fonts/Murecho/static/Murecho-Thin.ttf
    #     - asset: fonts/Murecho/Murecho-VariableFont_wght.ttf
  assets:
    - images/logo.png
    - images/landing_1.png
    - images/landing_2.png
    - images/landing_3.png
