name: pkm_gastreit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  provider: ^6.1.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  image_path: "images/logo.png" 

flutter:
  uses-material-design: true
  assets:
    - images/logo.png
    - images/landing_1.png
    - images/landing_2.png
    - images/landing_3.png
    - images/logo_google.png
    - images/Icon-InputCitra.png
    - images/Icon-HasilCitra.png
    - images/informasimenarik1.png
    - images/informasimenarik2.png
    - images/home_black.png
    - images/input_light.png
    - images/hasil_light.png
    - images/hasil_black.png
    - images/home_light.png
    - images/input_black.png

