// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzWsyfMKGNtu4_2sty_v9p5GNvqBQVyss',
    appId: '1:931693259084:web:ab450f124e735edcc687e9',
    messagingSenderId: '931693259084',
    projectId: 'pkmgastreit',
    authDomain: 'pkmgastreit.firebaseapp.com',
    storageBucket: 'pkmgastreit.appspot.com',
    measurementId: 'G-TSEDZCNSEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE3YKYYcwOjonTashZ4uz12L0zS6vCArQ',
    appId: '1:931693259084:android:58ce92c16f25b768c687e9',
    messagingSenderId: '931693259084',
    projectId: 'pkmgastreit',
    storageBucket: 'pkmgastreit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsSRoAKHanJSUwSeDRUpSNz4sLimW6BXQ',
    appId: '1:931693259084:ios:5a7a6335e0a3f9dbc687e9',
    messagingSenderId: '931693259084',
    projectId: 'pkmgastreit',
    storageBucket: 'pkmgastreit.appspot.com',
    iosBundleId: 'com.example.pkmGastreit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsSRoAKHanJSUwSeDRUpSNz4sLimW6BXQ',
    appId: '1:931693259084:ios:5a7a6335e0a3f9dbc687e9',
    messagingSenderId: '931693259084',
    projectId: 'pkmgastreit',
    storageBucket: 'pkmgastreit.appspot.com',
    iosBundleId: 'com.example.pkmGastreit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzWsyfMKGNtu4_2sty_v9p5GNvqBQVyss',
    appId: '1:931693259084:web:8ff459b6a5d192f0c687e9',
    messagingSenderId: '931693259084',
    projectId: 'pkmgastreit',
    authDomain: 'pkmgastreit.firebaseapp.com',
    storageBucket: 'pkmgastreit.appspot.com',
    measurementId: 'G-1BL1VJYS1X',
  );
}
